name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - src/**
      - tools/build.sh
      - .github/workflows/deploy-to-github-pages.yml
concurrency:
  group: deploy-to-github-pages
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - run: pipx install bikeshed && bikeshed update
      - run: tools/build.sh
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - id: deploy-pages
        uses: actions/deploy-pages@v1
